### ISSUE TITLE
Not installed

### ISSUE THREAD

**Issue by SequelONE** [renoki-co/jetstream-cashier-billing-portal#17]
I have problem with install. 

**Executing a command:**
```
php artisan billing-portal:install
```

**Error:**
```
Not enough arguments (missing: "stack").
```

**Laravel version:** 8.0
**PHP:** 7.3
**MySQL:** 8
**Composer:** 1.10.20

**Comment by SequelONE** [comment]
It's work for me!

```php artisan billing-portal:install stack```

**Comment by rennokki** [comment]
The idea was to specify the stack name:

```bash
$ php artisan billing-portal:install inertia
```

**Comment by SequelONE** [comment]
Could you add this point to the documentation?
