### ISSUE TITLE
Errors with routing about User model.

### ISSUE THREAD

**Issue by SequelONE** [renoki-co/jetstream-cashier-billing-portal#18]
**/user/billing/subscription**
```
Call to undefined method App\Models\User::subscription()
```

**/user/billing/portal**
```
Call to undefined method App\Models\User::createOrGetStripeCustomer()
```

**Comment by JamirHossainAfridi** [comment]
i also stuck on this problem.

**Comment by rennokki** [comment]
Package version? Laravel version?

**Comment by SequelONE** [comment]
> Package version? Laravel version?

```
"renoki-co/jetstream-cashier-billing-portal": "^3.1",
"laravel/framework": "^8.12",
```

**Comment by rennokki** [comment]
Have you recently upgraded from package 2.x to 3.x?

**Comment by rennokki** [comment]
Make sure to also install Cashier for Stripe in the project, including the Billable trait and the tables, because Cashier Billing Portal does not install them for you: https://laravel.com/docs/8.x/billing

**Comment by SequelONE** [comment]
> Have you recently upgraded from package 2.x to 3.x?

No. I installed according to the documentation on the newly installed Laravel.

> Make sure to also install Cashier for Stripe in the project, including the Billable trait and the tables, because Cashier Billing Portal does not install them for you: https://laravel.com/docs/8.x/billing

"laravel/cashier": "^12.9",

**Comment by rennokki** [comment]
You still need to prepare the models: https://laravel.com/docs/8.x/billing#billable-model
