### ISSUE TITLE
Prevent cors erros from redirects

### ISSUE THREAD

**Issue by Atiladanvi** [renoki-co/jetstream-cashier-billing-portal#9]
Why use `Redirect` instead `Inertia::location()` ? 
Why use `response('', 409)->header('X-Inertia-Location', $url)` if
`response('', 409)->header('X-Inertia-Location', $url) `is equals  `Inertia::location($url) `?
Why the `$asResponse` ? if 
```php
  return $asResponse
            ? response('', 409)->header('X-Inertia-Location', $url)
            : Redirect::to($url);
```
Always goes return: `Redirect::to($url)`.

Bad things can happen if we combine `$inertia.visit` with:
https://github.com/renoki-co/jetstream-cashier-billing-portal/blob/be606052b5b0ccb952e81313a4d7f119342c74d2/src/Http/Controllers/Inertia/BillingController.php#L41
![image](https://user-images.githubusercontent.com/11599205/113657823-2457b580-9675-11eb-99e8-733314ef1cc1.png)

What to do to prevent evetuals cors erros ?
`Redirect::to($url)` works in your installation ?

**Comment by rennokki** [comment]
The feature was before this: https://github.com/inertiajs/inertia/issues/99#issuecomment-702823742

**Comment by rennokki** [comment]
The update (either 2.x or 3.x) requires Jetstream ^2.3
